# Generated by Django 5.1.4 on 2025-02-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
