# Generated by Django 5.1.4 on 2025-03-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='login_requires',
            field=models.BooleanField(default=False),
        ),
    ]
